project:
  type: website
  output-dir: _site

website:
  title: "Yusuf Kurnia Romadhon"
  description: "Communicating with Data - Personal Site and Blog"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: posts/
    right:
      - icon: github
        aria-label: GitHub
        href: https://github.com/yusufkurniar01
  page-footer:
    left: "© {{< 2025 >}} Yusuf Kurnia Romadhon"
    right: "Built with Quarto"

format:
  html:
    theme:
      light: [cosmo, styles/custom.scss]
      dark: [cosmo, styles/custom.scss]
    toc: true
    toc-location: left
    number-sections: false
    code-tools: true



